### ISSUE TITLE
Issue to build

### ISSUE THREAD

**Issue by Elsa-Athel** [super-high/solana-staking#50]
I was trying to build project
But I get this result:
-- > Anchor build Error: No such file or directory (os error 2) <--

please let me know how to solve this error

**Comment by super-high** [comment]
what is your OS

**Comment by King-Mufasa** [comment]
it seems your anchor is not installed correctly.
Please install rust first and init project again.

**Comment by Elsa-Athel** [comment]
Thank you Mufasa, you saved me
